"""
Purpose: Generates TypeScript declaration files (.d.ts) for ucode.
Phase: Indexing
Layers: L3
Inputs: OUTDIR/cross-link-registry.json
Outputs: OUTDIR/ucode/ucode.d.ts
Environment Variables: OUTDIR
Dependencies: lib.config
Notes: Strictly for the ucode module. Groups symbols by their base module (e.g. fs, uloop).
"""

import json
import os
import re
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))
from lib import config

sys.stdout.reconfigure(line_buffering=True)

OUTDIR = config.OUTDIR
REGISTRY_PATH = os.path.join(OUTDIR, "cross-link-registry.json")
RELEASE_TREE_DIR = config.RELEASE_TREE_DIR

print("[05c] Generating ucode.d.ts IDE schemas")

if not os.path.isfile(REGISTRY_PATH):
    print(f"[05c] FAIL: cross-link-registry.json not found at {REGISTRY_PATH}")
    sys.exit(1)

try:
    with open(REGISTRY_PATH, "r", encoding="utf-8") as f:
        registry = json.load(f)
except Exception as e:
    print(f"[05c] FAIL: Could not parse registry: {e}")
    sys.exit(1)

# Filter for ucode symbols only
# Symbols in the registry have relative_target like "../ucode/..."
ucode_symbols = {}
for sym, meta in registry.get("symbols", {}).items():
    if "/ucode/" in meta.get("relative_target", ""):
        ucode_symbols[sym] = meta

if not ucode_symbols:
    print("[05c] INFO: No ucode symbols found in registry. Skipping .d.ts generation.")
    sys.exit(0)

# Group by base module (e.g., 'fs' from 'fs.open')
modules = {}
for sym, meta in ucode_symbols.items():
    if "." in sym:
        mod_name, func_name = sym.split(".", 1)
    else:
        mod_name = "global"
        func_name = sym

    if mod_name not in modules:
        modules[mod_name] = []

    modules[mod_name].append({
        "name": func_name,
        "sig": meta.get("signature", f"{func_name}()"),
        "returns": meta.get("returns", "any"),
        "desc": meta.get("ai_summary") or meta.get("description"),
    })

def generate_ts_sig(f, is_global=False):
    """Normalize signature for simple TS: foo(a, [b]) -> foo(a: any, b?: any)"""
    sig = f['sig']
    prefix = "declare function " if is_global else "export function "

    if "(" in sig and ")" in sig:
        params_str = sig.split("(", 1)[1].rsplit(")", 1)[0]
        ts_params = []

        if params_str.strip():
            # Handle balanced splitting (BUG-016)
            params = []
            current = []
            bracket_level = 0
            for char in params_str:
                if char == "," and bracket_level == 0:
                    params.append("".join(current).strip())
                    current = []
                else:
                    if char in "[({":
                        bracket_level += 1
                    if char in "])}":
                        bracket_level -= 1
                    current.append(char)
            params.append("".join(current).strip())

            for p in params:
                # FIX BUG-016: Handle optional [param] notation
                is_optional = False
                p_name = p.split("=")[0].strip()
                if p_name.startswith("[") and p_name.endswith("]"):
                    p_name = p_name[1:-1].strip()
                    is_optional = True

                # Cleanup name (no special chars)
                p_name = re.sub(r"[^a-zA-Z0-9_]", "_", p_name)
                ts_params.append(f"{p_name}{'?' if is_optional else ''}: any")

        # FIX BUG-016: Append return type
        return f"{prefix}{f['name']}({', '.join(ts_params)}): {f['returns']};"
    else:
        return f"{prefix}{f['name']}(...args: any[]): {f['returns']};"

# Construct .d.ts content
dts_lines = [
    "/**",
    " * AUTOGENERATED VIA openwrt-docs4ai",
    " * Target: Language Server Protocol (LSP) IDE Autocomplete",
    " */",
    ""
]

for mod_name, funcs in sorted(modules.items()):
    if mod_name == "global":
        for f in sorted(funcs, key=lambda x: x["name"]):
            if f.get("desc"):
                dts_lines.append(f"/** {f['desc']} */")
            dts_lines.append(generate_ts_sig(f, is_global=True))
    else:
        dts_lines.append(f'declare module "{mod_name}" {{')
        for f in sorted(funcs, key=lambda x: x["name"]):
            if f.get("desc"):
                dts_lines.append("    /**")
                dts_lines.append(f"     * {f['desc']}")
                dts_lines.append("     */")
            dts_lines.append(f"    {generate_ts_sig(f, is_global=False)}")
        dts_lines.append("}")
    dts_lines.append("")

out_dir = os.path.join(OUTDIR, "ucode")
os.makedirs(out_dir, exist_ok=True)
out_path = os.path.join(out_dir, "ucode.d.ts")

with open(out_path, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(dts_lines))

release_types_dir = os.path.join(RELEASE_TREE_DIR, "ucode", config.MODULE_TYPES_DIRNAME)
os.makedirs(release_types_dir, exist_ok=True)
release_out_path = os.path.join(release_types_dir, "ucode.d.ts")

with open(release_out_path, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(dts_lines))

print(f"[05c] OK: {out_path}, {release_out_path} ({len(ucode_symbols)} symbols)")
