import os
import re
import json
import argparse
from datetime import datetime
from openai import OpenAI
from pydantic import BaseModel
from typing import List

# 1. Define the Expected JSON Output Structure for the Auditor
class EvaluationResult(BaseModel):
    passed: bool
    failure_explanation: str
    classified_error_types: List[str]

# 2. Hardcode the Auditor Prompt
AUDITOR_SYSTEM_PROMPT = """You are an Expert OpenWrt Code Auditor. Your job is to evaluate code snippets generated by a junior AI and categorize its failures according to our strict OpenWrt taxonomy.
You must return your evaluation complying strictly with the requested JSON schema.

APPROVED TAXONOMY LIBRARY:
- "ERR_LINUX_HALLUCINATION": Uses standard Linux utilities (systemd, ip, apt etc) instead of OpenWrt standards (procd, ubus, uci).
- "ERR_LEGACY_API": Uses deprecated paradigms (Lua CBI instead of LuCI JS).
- "ERR_MISSING_BOILERPLATE": Missing OpenWrt structure (USE_PROCD=1, uloop, libubus.h).
- "ERR_STATE_MANAGEMENT": Maintains state via flat files instead of uci.
- "ERR_NON_C_COMPLIANT": Uses standard sleep/while loops instead of uloop in C.
"""

def load_scenarios():
    prompt_file = "../scenarios/01-batch-prompts.md"
    metadata_file = "../scenarios/02-metadata-catalog.json"
    
    with open(metadata_file, "r") as f:
        metadata = json.load(f)
        
    with open(prompt_file, "r") as f:
        content = f.read()

    # Regex to extract the text between "## Scenario XX" and "---"
    scenarios = {}
    pattern = re.compile(r"## (Scenario \d+)(.*?)(?=---|\Z)", re.DOTALL)
    for match in pattern.finditer(content):
        scenario_id = match.group(1).strip()
        scenario_prompt = match.group(2).strip()
        
        scenarios[scenario_id] = {
            "prompt": scenario_prompt,
            "metadata": metadata.get(scenario_id, {})
        }
    return scenarios

def run_pipeline(target_model: str, auditor_model: str):
    client = OpenAI()
    scenarios = load_scenarios()
    
    results = {}
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    os.makedirs("../results", exist_ok=True)

    print(f"Starting pipeline run at {timestamp}")
    print(f"Target Agent: {target_model} | Evaluating Agent: {auditor_model}\n")

    for scenario_id, data in scenarios.items():
        print(f"[{scenario_id}] Phase 1: Generating standard response...")
        prompt = data["prompt"]
        
        try:
            gen_response = client.chat.completions.create(
                model=target_model,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.7 
            )
            generated_code = gen_response.choices[0].message.content
        except Exception as e:
            print(f"Failed to generate code for {scenario_id}: {e}")
            continue

        print(f"[{scenario_id}] Phase 2: Auditing generated code...")

        audit_user_prompt = f"ORIGINAL REQUEST:\n{prompt}\n\nGENERATED CODE TO AUDIT:\n{generated_code}\n\nEXPECTED PARADIGMS IT MUST CONTAIN:\n{data['metadata'].get('expected_paradigms', [])}"
        
        try:
            audit_response = client.beta.chat.completions.parse(
                model=auditor_model,
                messages=[
                    {"role": "system", "content": AUDITOR_SYSTEM_PROMPT},
                    {"role": "user", "content": audit_user_prompt}
                ],
                response_format=EvaluationResult,
                temperature=0.0
            )
            
            evaluation = audit_response.choices[0].message.parsed
            
            results[scenario_id] = {
                "prompt": prompt,
                "generated_code": generated_code,
                "evaluation": {
                    "passed": evaluation.passed,
                    "failure_explanation": evaluation.failure_explanation,
                    "classified_error_types": evaluation.classified_error_types
                }
            }
            
            status = "PASS" if evaluation.passed else "FAIL"
            print(f"[{scenario_id}] Complete. Status: {status}. Errors: {evaluation.classified_error_types}\n")
            
        except Exception as e:
            print(f"Failed to audit code for {scenario_id}: {e}")

    report_file = f"../results/eval_report_{timestamp}.json"
    with open(report_file, "w") as f:
        json.dump(results, f, indent=4)
        
    print(f"Pipeline finished! Full dynamic scoresheet written to: {report_file}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="OpenWrt AI Defect Discovery Harness")
    parser.add_argument("--target-model", type=str, default="gpt-4o-mini", help="The AI generating the code")
    parser.add_argument("--auditor-model", type=str, default="gpt-4o", help="The strict AI auditing the code")
    args = parser.parse_args()
    
    run_pipeline(args.target_model, args.auditor_model)
